CREATE TABLE person (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
age INTEGER NOT NULL CHECK (age > 0),
has_license BOOLEAN NOT NULL DEFAULT false);

CREATE TABLE car (
id SERIAL PRIMARY KEY,
brand VARCHAR(255) NOT NULL,
model VARCHAR(255) NOT NULL,
price NUMERIC(10,2) NOT NULL);

CREATE TABLE person_car (
id SERIAL PRIMARY KEY,
person_id INTEGER REFERENCES person(id) ON DELETE CASCADE,
car_id INTEGER REFERENCES car(id) ON DELETE CASCADE);